---
- hosts: all
  become: true

  tasks:
    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"


    - hosts: server
      become: yes
      connection: ssh
      tasks:
        - name: install httpd on ubuntu
          command: apt-get install apache2 -y
          when: ansible_os_family="ubuntu"
      tasks:
        - name: install httpd on amazon
          command: yum install httpd -y
          when: ansible_os_family=“redhat”
      tasks:
        - name: service
          state: restart
